name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fileenv: # This workflow contains a single job called "build"
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Enter data to .env file
      run: |
        echo GATSBY_FLOTIQ_BASE_URL=https://api.flotiq.com >> .env
        echo FLOTIQ_API_KEY="$FLOTIQ_API_KEY" >> .env
      shell: bash
      env:
        FLOTIQ_API_KEY: ${{ secrets.FLOTIQ_API_KEY }}
    - uses: actions/upload-artifact@v1
      with:
        name: file .env
        path: .env
        
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download file .env result for fileenv
    - uses: actions/download-artifact@v1
      with:
        name: file .env
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Gatsby
      run: | 
        npm install -g gatsby-cli
        gatsby clean
        gatsby build
    - uses: actions/upload-artifact@v1
      with:
          name: gatsbypublic
          path: ./public
        
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Download directory result for job build
    - uses: actions/download-artifact@v1
      with:
        name: gatsbypublic
    - name: Cloudflare
      run: |
        npm install -g @cloudflare/wrangler
        wrangler init --site my-static-site
        sed 's+account_id = ""+account_id = '"'"$ACCOUNT_ID"'"'+g' wrangler.toml > temp1
        sed 's+bucket = ""+bucket = "./public"+g' temp1 > wrangler.toml
        mkdir -p /home/runner/.wrangler/config/
        echo api_token = '"'"$API_TOKEN"'"' > /home/runner/.wrangler/config/default.toml
        wrangler publish
      shell: bash
      env: # Or as an environment variable
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
